// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tracker.Api.Data;

#nullable disable

namespace Tracker.Api.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    partial class TrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tracker.Api.Models.Project", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Description")
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.ToTable("Projects");
            });

            modelBuilder.Entity("Tracker.Api.Models.Settings", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid?>("DefaultProjectId")
                    .HasColumnType("uuid");

                b.Property<string>("DigestTime")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("text")
                    .HasDefaultValue("09:00");

                b.Property<string>("GithubWebhookSecret")
                    .HasColumnType("text");

                b.Property<string>("TelegramChatId")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Settings");
            });

            modelBuilder.Entity("Tracker.Api.Models.Sprint", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateOnly?>("EndDate")
                    .HasColumnType("date");

                b.Property<bool>("IsActive")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasDefaultValue(false);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<Guid>("ProjectId")
                    .HasColumnType("uuid");

                b.Property<DateOnly?>("StartDate")
                    .HasColumnType("date");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("ProjectId");

                b.ToTable("Sprints");
            });

            modelBuilder.Entity("Tracker.Api.Models.TaskItem", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Assignee")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("Column")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasDefaultValue("Backlog");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("GithubIssueUrl")
                    .HasColumnType("text");

                b.Property<string>("GithubPrUrl")
                    .HasColumnType("text");

                b.Property<int>("Position")
                    .HasColumnType("integer");

                b.Property<string>("Priority")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasDefaultValue("medium");

                b.Property<Guid>("ProjectId")
                    .HasColumnType("uuid");

                b.Property<Guid?>("SprintId")
                    .HasColumnType("uuid");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<string>("Type")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasDefaultValue("feature");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("ProjectId");

                b.HasIndex("SprintId");

                b.ToTable("Tasks");
            });

            modelBuilder.Entity("Tracker.Api.Models.Sprint", b =>
            {
                b.HasOne("Tracker.Api.Models.Project", "Project")
                    .WithMany("Sprints")
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Project");
            });

            modelBuilder.Entity("Tracker.Api.Models.TaskItem", b =>
            {
                b.HasOne("Tracker.Api.Models.Project", "Project")
                    .WithMany("Tasks")
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Tracker.Api.Models.Sprint", "Sprint")
                    .WithMany("Tasks")
                    .HasForeignKey("SprintId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.Navigation("Project");

                b.Navigation("Sprint");
            });

            modelBuilder.Entity("Tracker.Api.Models.Project", b =>
            {
                b.Navigation("Sprints");
                b.Navigation("Tasks");
            });

            modelBuilder.Entity("Tracker.Api.Models.Sprint", b =>
            {
                b.Navigation("Tasks");
            });
#pragma warning restore 612, 618
        }
    }
}
